fixtures:
  symlinks:
    role: '#{source_dir}'
    profile: '#{source_dir}/../profile'
  repositories:
    dataprep_dataset:
      repo: "https://github.com/Talend/puppet-dataprep_dataset"
      ref: "development"
  forge_modules:
    archive: "puppet-archive"
    selinux: "jfryman/selinux"
    stdlib: "puppetlabs/stdlib"
    concat: "puppetlabs/concat"
    awscli: "jdowning/awscli"
    epel: "stahnma/epel"
    nginx: "jfryman/nginx"
    staging: "nanliu/staging"
    apt: "puppetlabs/apt"
    shellvar: "herculesteam/augeasproviders_shellvar"
    auges_core: "herculesteam/augeasproviders_core"
    packagecloud: "computology/packagecloud"
    tomcat:
      repo: "puppetlabs/tomcat"
      ref: "1.5.0"
    java:
      repo: "puppetlabs/java"
      ref: "1.5.0"
    mongodb:
      repo: "puppetlabs/mongodb"
      ref: "0.13.0"
    nexus:
      repo: "hubspot/nexus"
      ref: "1.3.3 "
    wget:
     repo: "maestrodev/wget"
     ref: "1.7.3"
