require 'rubygems'
require 'rake'
require 'puppetlabs_spec_helper/rake_tasks'
require 'puppet-lint/tasks/puppet-lint'
require 'puppet-syntax/tasks/puppet-syntax'

exclude_paths = [
  "pkg/**/*",
  "vendor/**/*",
  "spec/**/*",
  "contrib/**/*"
]

# Make sure we don't have the default rake task floating around
Rake::Task['lint'].clear

PuppetLint.configuration.relative = true
PuppetLint::RakeTask.new(:lint) do |l|
  l.disable_checks = %w(80chars class_inherits_from_params_class)
  l.ignore_paths = exclude_paths
  l.fail_on_warnings = true
  l.log_format = "FUK %{path}:%{linenumber}:%{check}:%{KIND}:%{message}"
end

PuppetSyntax.exclude_paths = exclude_paths

task :default => [:lint, :validate, :spec]

# Define separate rake task for every role spec
# TODO: revise this in favor of more sophisticated solution
#       at the moment it looks like that it should be beaker
#       native tests (so, no beaker-rspec/serverspec) OR
#       test-kitchen with kitchen-puppet
Dir['spec/acceptance/**/role_*_spec.rb'].sort.map do |role_spec|
  /role_(.*?)_spec\.rb/.match(File.basename(role_spec))[1]
end.each do |role|
  desc "Run beaker for #{role} spec only"
  RSpec::Core::RakeTask.new("beaker:role:#{role}") do |t|
    t.rspec_opts = ['--color']
    t.pattern = "spec/acceptance/**/role_#{role}_spec.rb"
  end
end
