fixtures:
  symlinks:
    profile: '#{source_dir}'
  forge_modules:
    selinux: "jfryman/selinux"
    archive: "puppet-archive"
    concat: "puppetlabs/concat"
    awscli: "jdowning/awscli"
    stdlib: "puppetlabs/stdlib"
    epel: "stahnma/epel"
    nginx: "jfryman/nginx"
    staging: "nanliu/staging"
    tomcat:
      repo: "puppetlabs/tomcat"
      ref: "1.5.0"
    java:
      repo: "puppetlabs/java"
      ref: "1.5.0"
    apt: "puppetlabs/apt"
    mongodb:
      repo: "puppetlabs/mongodb"
      ref: "0.13.0"
    nexus:
      repo: "hubspot/nexus"
      ref: "1.3.3 "
    wget:
     repo: "maestrodev/wget"
     ref: "1.7.3"
